#!/usr/bin/env bash
# remove_worker.sh — Linux port of the cleanup functionality
#
# Removes Steam artifacts associated with a LuaTools install.

set -u

# ADAPT-LINUX: clear Steam-runtime env vars
unset LD_LIBRARY_PATH LD_PRELOAD LD_AUDIT STEAM_RUNTIME_LIBRARY_PATH STEAM_ZENITY

APP_ID=""
STEAM_PATH=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --app-id) APP_ID="$2"; shift 2 ;;
    --steam-path) STEAM_PATH="$2"; shift 2 ;;
    *) shift ;;
  esac
done

if [[ -z "$APP_ID" || ! "$APP_ID" =~ ^[0-9]+$ || -z "$STEAM_PATH" ]]; then
  exit 1
fi

install_path=""
acf_file=""

# Find library paths
libroots=("$STEAM_PATH/steamapps")
LIBVDF="$STEAM_PATH/steamapps/libraryfolders.vdf"
if [[ -f "$LIBVDF" ]]; then
  while IFS= read -r p; do
    [[ -n "$p" ]] && libroots+=("$p/steamapps")
  done < <(grep -oE '"path"[[:space:]]*"[^"]+"' "$LIBVDF" | sed -E 's/.*"path"[[:space:]]*"([^"]+)".*/\1/')
fi

# Find the game installation directory and ACF file
for lib in "${libroots[@]}"; do
  acf="${lib}/appmanifest_${APP_ID}.acf"
  if [[ -f "$acf" ]]; then
    installdir=$(grep -oE '"installdir"[[:space:]]*"[^"]+"' "$acf" | head -n1 | sed -E 's/.*"installdir"[[:space:]]*"([^"]+)".*/\1/')
    if [[ -n "$installdir" ]]; then
      install_path="${lib}/common/${installdir}"
      acf_file="$acf"
      break
    fi
  fi
done

# Step 1: Delete game folder
if [[ -n "$install_path" && -d "$install_path" ]]; then
  rm -rf "$install_path"
fi

# Step 2: Delete appmanifest
if [[ -n "$acf_file" && -f "$acf_file" ]]; then
  rm -f "$acf_file"
fi

# Extract depot IDs from the Lua script (before it is deleted by main.lua)
LUA_FILE="$STEAM_PATH/config/stplug-in/${APP_ID}.lua"
if [[ -f "$LUA_FILE" ]]; then
  # Matches setManifestid(depot_id, ...) and extracts depot_id
  depot_ids=($(grep -oE 'setManifestid\([[:space:]]*[0-9]+' "$LUA_FILE" | grep -oE '[0-9]+'))
  
  for depot in "${depot_ids[@]}"; do
    # Step 3: Delete downloaded manifests in depotcache
    rm -f "$STEAM_PATH/depotcache/${depot}_"*.manifest
    
    # Step 5a: Delete manifestID cache generated by SLSsteam
    rm -f "$HOME/.local/share/SLSsteam/cache/manifestid_${depot}.yaml"
  done
fi

# Step 5b: Delete PICS cache for the app
rm -f "$HOME/.local/share/SLSsteam/cache/pics_app_${APP_ID}.bin"

exit 0
